### ISSUE TITLE
Support LIST request method

### ISSUE THREAD

**Issue by roooms** [hashicorp/hcdiag#158]
Some vault endpoints use `LIST` rather than `GET` eg [listing automated snapshots configuration](https://www.vaultproject.io/api-docs/system/storage/raftautosnapshots#list-automated-snapshots-configs), which would be useful for hcdiag to support.

**Comment by roooms** [comment]
I've just learned that you can handle this specifically for the vault case with a querystring addition to the request:

```
LIST /v1/sys/storage/raft/snapshot-auto/config
```
can be replaced with 
```
GET /v1/sys/storage/raft/snapshot-auto/config?list=true
```

This works around the issue for vault, but `LIST` support may be useful elsewhere.

**Comment by aliciaclark1066** [comment]
@roooms As there is a workaround to this and Vault plans to deprecate LIST functionality in the future. We've decided not to work on this item. Thanks!
