### ISSUE TITLE
Add a function to query a postgresql database

### ISSUE THREAD

**Issue by anniehedgpeth** [hashicorp/hcdiag#175]
**What problem would you like `hcdiag` to address?**  
The TFE product and engineering team would like to use `hcdiag` to gather data on what types of environments our customers are running TFE in ([PRD](https://docs.google.com/document/d/1yCoD2EAIoi6w89IJ4aefAAAssDd75fQRzffvT10H5xM/edit?usp=sharing), [RFC](https://docs.google.com/document/d/1rq6wvO8lfYya30zIZUKI7bmofDvhkyUkXt-YrwJe3SU/edit?usp=sharing)). Most of the data will be collected from Replicated and TFE config, however, we are not able to gather data about the type of database they are using.

**Who is the audience for this request?**  
Internal - TFE team

**What would the ideal solution look like?**  
We would like to have a function that is able to authenticate and write queries to the database in order to gather data. Ideally, we would also be able to define the key that this is stored as as something readable as opposed to the query being the key.

**What alternatives have you considered?**  
I did not look into this thoroughly because it will not be suitable, but running `psql "host=mydb.postgres.database.azure.com port=5432 dbname=postgres user=tfeuser sslmode=require" -c "SELECT version();"` with the `sheller` seeker would give me the output I need, however, I would need a way to inject the database connection string as a variable. Also, I _believe_ that special characters in the password would need to be escaped.

**What is the impact?**  
As I noted in the [RFC](https://docs.google.com/document/d/1rq6wvO8lfYya30zIZUKI7bmofDvhkyUkXt-YrwJe3SU/edit?usp=sharing), there is an entire section (called "Suggest Dropping" at the bottom of the doc) of system level data that would be nice to have but we are dropping from our initiative because there is not a sane way to gather cloud data from customers (especially from the TFE instance). However, getting a few small bits of data about the database would be really valuable in assessing the overall picture of what our customers' environments look like.

**Comment by aliciaclark1066** [comment]
Thanks Annie! This is great info for us. We'll take a look and get back to you soon on when we can prioritize this request.

**Comment by aliciaclark1066** [comment]
As discussed, we'll have similar issues implementing this ticket and won't be able to complete this. Closing ticket.
