### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by anniehedgpeth** [hashicorp/hcdiag#182]
**What problem would you like `hcdiag` to address?**  
I would like for the `httper` seeker to be able to iterate through all pages of an API response.

**Who is the audience for this request?**  
TFE engineering team

**What would the ideal solution look like?**  
Ideally, we would like to be able to request to see all organizations, users, workspaces, etc. and that `hcdiag` would be able to iterate through the pagination in order to retrieve them.

**What alternatives have you considered?**
At first we thought that we may only need the `meta.status-counts` for the purposes of data collection (RE: [TF-533](https://docs.google.com/document/d/1rq6wvO8lfYya30zIZUKI7bmofDvhkyUkXt-YrwJe3SU/edit)) so we'd only need to return the first page, however there will certainly be situations in which we'll need more data when troubleshooting customers' environments and iterating through each of the pages to retrieve all of the data will be necessary.

**What is the impact?**  
(Explained in previous question.)

**Comment by aliciaclark1066** [comment]
Per customer confirmation, this is no longer needed.
