### ISSUE TITLE
Multiline output not in results and second pipe not allowed

### ISSUE THREAD

**Issue by anniehedgpeth** [hashicorp/hcdiag#187]
**What is the bug?**

While using the Sheller, piping seems to only be allowed once, and when output is in json format, it is not printing in the results.

**When does the error occur?**  

I have tried formatting my command several different ways and have tried using both the Commander and Sheller. Unfortunately, I cannot use the Commander because of a Replicated bug where their json output has whitespace that must be trimmed from it:

```go
runner.NewCommander("replicated admin list-nodes", "json", nil),
```

...results in the following error:

```
2022-08-09T18:39:21.826Z [WARN]  hcdiag.product: result: runner="replicated admin list-nodes" status=unknown result="" error="json.Unmarshal(...) error, command=replicated admin list-nodes, error=unexpected end of JSON input"
```

When I run the same command with the Sheller runner like so:

```go
runner.NewSheller("replicated admin list-nodes", nil),
```

...the result status is a success, but the actual result is an empty string.

```json
"replicated admin list-nodes": {
    "result": "",
    "error": "",
    "status": "success",
    "params": {
        "command": "replicated admin list-nodes",
        "redactions": null,
        "shell": "/bin/bash"
    }
},
```

When I try to trim the whitespace off of the end of the json, like so:

```go
runner.NewSheller("replicated admin list-nodes | tr -d '\r'", nil),
```

...I get the same results...

```json
"replicated admin list-nodes | tr -d '\r'": {
    "result": "",
    "error": "",
    "status": "success",
    "params": {
        "command": "replicated admin list-nodes | tr -d '\r'",
        "redactions": null,
        "shell": "/bin/bash"
    }
},
```

I tried to pipe the results of the previous command to `jq` for json output, which would have still only printed a string, but I wanted to see what would change in the output, so I tried:

```go
runner.NewSheller("replicated admin list-nodes | tr -d '\r' | jq", nil),
```

...but it seems to have broken the pipe before the `jq`

```
2022-08-08T22:34:16.953Z [WARN]  hcdiag.product: result: runner="replicated admin list-nodes | tr -d '\r' | jq" status=unknown
  result=
  | jq - commandline JSON processor [version 1.5]
  | Usage: jq [options] <jq filter> [file...]
  | 
  |     jq is a tool for processing JSON inputs, applying the
  |     given filter to its JSON text inputs and producing the
  |     filter's results as JSON on standard output.
  |     The simplest filter is ., which is the identity filter,
  |     copying jq's input to its output unmodified (except for
  |     formatting).
  |     For more advanced filters see the jq(1) manpage ("man jq")
  |     and/or https://stedolan.github.io/jq
  | 
  |     Some of the options include:
  |      -c             compact instead of pretty-printed output;
  |      -n             use `null` as the single input value;
  |      -e             set the exit status code based on the output;
  |      -s             read (slurp) all inputs into an array; apply filter to it;
  |      -r             output raw strings, not JSON texts;
  |      -R             read raw strings, not JSON texts;
  |      -C             colorize JSON;
  |      -M             monochrome (don't colorize JSON);
  |      -S             sort keys of objects on output;
  |      --tab  use tabs for indentation;
  |      --arg a v      set variable $a to value <v>;
  |      --argjson a v  set variable $a to JSON value <v>;
  |      --slurpfile a f        set variable $a to an array of JSON texts read from <f>;
  |     See the manpage for more options.
   error="exec error, command=replicated admin list-nodes | tr -d '\r' | jq, error=exit status 2"
```

...and the Results.json contains the same output which is just the output of a single `jq` command...

```json
        "replicated admin list-nodes | tr -d '\r' | jq": {
            "result": "jq - commandline JSON processor [version 1.5]\nUsage: jq [options] \u003cjq filter\u003e [file...]\n\n\tjq is a tool for processing JSON inputs, applying the\n\tgiven filter to its JSON text inputs and producing the\n\tfilter's results as JSON on standard output.\n\tThe simplest filter is ., which is the identity filter,\n\tcopying jq's input to its output unmodified (except for\n\tformatting).\n\tFor more advanced filters see the jq(1) manpage (\"man jq\")\n\tand/or https://stedolan.github.io/jq\n\n\tSome of the options include:\n\t -c\t\tcompact instead of pretty-printed output;\n\t -n\t\tuse `null` as the single input value;\n\t -e\t\tset the exit status code based on the output;\n\t -s\t\tread (slurp) all inputs into an array; apply filter to it;\n\t -r\t\toutput raw strings, not JSON texts;\n\t -R\t\tread raw strings, not JSON texts;\n\t -C\t\tcolorize JSON;\n\t -M\t\tmonochrome (don't colorize JSON);\n\t -S\t\tsort keys of objects on output;\n\t --tab\tuse tabs for indentation;\n\t --arg a v\tset variable $a to value \u003cv\u003e;\n\t --argjson a v\tset variable $a to JSON value \u003cv\u003e;\n\t --slurpfile a f\tset variable $a to an array of JSON texts read from \u003cf\u003e;\n\tSee the manpage for more options.\n",
            "error": "exec error, command=replicated admin list-nodes | tr -d '\r' | jq, error=exit status 2",
            "status": "unknown",
            "params": {
                "command": "replicated admin list-nodes | tr -d '\r' | jq",
                "redactions": null,
                "shell": "/bin/bash"
            }
        },
```

**What is the expected behavior?**  
The command to get the output I need is this:
```
replicated admin list-nodes
```

But I am not able to get a runner to gather its output properly, which would look something like this:

```
[
  "10.0.32.4"
]
```

I'm happy to trim the whitespace if needed, too, but as I've noted, that hasn't worked either.

**Is there a workaround?**
Not gathering this data. Perhaps there's a variation of this command that I haven't tried yet that will result in the desired output, but I don't know what that is.

**What is the impact?**
We cannot gather data on how many active TFE nodes a customer is using.

**What version are you using?**  
`hcdiag v0.4.0-dev (3e03192+CHANGES), built Tue Aug  9 12:39:03 MDT 2022`

```
/tmp# replicated admin list-nodes | tr -d '\r' | jq
[
  "10.0.32.4"
]
```

**Is there any additional context?**  
No, but I'd like to add that it would be really nice if the Sheller runner was able to format the output as json if the output of the command was json.

**Comment by aliciaclark1066** [comment]
@roooms Hey Dan, you've done quite a bit of shell scripting with hcdiag. Is this an issue you've come across before?

**Comment by roooms** [comment]
I don't see an obvious way to get the output from this exact command. As Annie has tested, JSON and string don't seem to get it although the exit code is success. Looks like the sheller isn't very happy with the more complex command. I think @gulducat helped with some previous comand parsing improvements which might be possible in this instance.

While the output isn't very nice, does `replicated nodes` give you the information you need? This does succeed and provide a string output.

CLI result...
```
$ replicated nodes
ID                                  PRIVATE ADDRESS    PUBLIC ADDRESS    CONNECTED    INITIALIZED    VERSION    TAGS
f002132f2c404c5d583cbb152278ac7d    10.0.2.15                            true         true           2.53.7     workers
```

Results.json...
```
        "replicated nodes": {
            "runner": {
                "command": "replicated nodes"
            },
            "result": "ID                                  PRIVATE ADDRESS    PUBLIC ADDRESS    CONNECTED    INITIALIZED    VERSION    TAGS\nf002132f2c404c5d583cbb152278ac7d    10.0.2.15                            true         true           2.53.7     workers",
            "error": "",
            "status": "success"
        }
```

**Comment by anniehedgpeth** [comment]
Yeah, the problem with `replicated nodes` is that it doesn't know about the other nodes in an active/active installation. I ran both on an active/active TFE and got this:

```bash
root@ip-10-0-136-143:~# replicated nodes
ID                                  PRIVATE ADDRESS    PUBLIC ADDRESS    CONNECTED    INITIALIZED    VERSION    TAGS
0ff0329c7f3a443f6343142fb91fc327    10.0.136.143                         true         true           2.53.7     workers

root@ip-10-0-136-143:~# replicated admin list-nodes
[
  "10.0.66.82",
  "10.0.136.143"
]
```

**Comment by nwchandler** [comment]
Hi, @anniehedgpeth - just curious, is it possible that `replicated admin list-nodes` is outputting to stderr instead of stdout? I have done some quick testing using pipes and shellers on my machine, and it seems as though the pipes are working. (I don't have quick access to a TFE environment, so I'm doing `echo '["10.0.32.4"]' | tr -d '\r' | jq` and it succeeds. I'm wondering, though, whether the output is actually going to stderr, so that jq doesn't have anything it can operate on - at which point, it prints its usage info.

**Comment by anniehedgpeth** [comment]
Hey @nwchandler , sorry for the delayed response (was at our offsite). 

So it does appear that it's going to stderr (this is a standalone instance, not the active/active one from above):
```
root@ucim-vmss000000:/tmp/my_bundles/hcdiag-2022-09-07T222939Z# replicated admin list-nodes >/dev/null
root@ucim-vmss000000:/tmp/my_bundles/hcdiag-2022-09-07T222939Z# replicated admin list-nodes 2>/dev/null
[
  "10.0.32.4"
]
```

However, if I'm using the Sheller, shouldn't I see the output in the "error" field? I still see nothing, even when I'm not using jq.

**Comment by anniehedgpeth** [comment]
Also, @nwchandler , please DM me, and I am happy to help you get a TFE test instance!

**Comment by anniehedgpeth** [comment]
From @nwchandler [via Jira](https://hashicorp.atlassian.net/browse/DIAG-48?focusedCommentId=105567): 

> I’ve spent some time digging into this, and I think I’ve figured out what’s going on. The replicated “command” is actually a bash script that does some command line parsing and then wraps a call to a Docker execution of a replicated container using flags provided by the script to alter its behavior. It seems that, by default, the script assumes that is being called directly by a user within a terminal, which is usually the right call! :slight_smile: However, when executed by hcdiag, it is actually NOT within a terminal, leading to a disconnect between the output from the container and hcdiag. Thankfully, the script provides a flag to tell it NOT to have Docker allocate a tty for the container; --no-tty. I confirmed that when this flag is passed, it is possible to get the list of nodes successfully with hcdiag using a Commander (no sheller needed), using format=JSON and command replicated --no-tty admin list-nodes.

> Note that I also found in the replicated documents a bit more detail as to why/when to pass the --no-tty flag to their container: [Admin Commands](https://help.shipyard.tools/docs/swarm/packaging-an-application/admin-commands/#cli-script-flags)

I tested it out on PR #247, and it works great! Many thanks! And with that I'll close the ticket. :)

**Comment by nwchandler** [comment]
For reference, I've also added to the FAQ in case anyone runs into issues in the future with commands not producing any results when run by hcdiag, even when they work just fine in a terminal. Hopefully this link won't break, but it can be found [here](https://github.com/hashicorp/hcdiag/blob/main/docs/faq.md#why-are-the-results-of-my-command-or-shell-runner-empty-when-the-command-works-if-i-run-it-in-my-terminal).
