### ISSUE TITLE
Cloud Metrics Retrieval

### ISSUE THREAD

**Issue by anniehedgpeth** [hashicorp/hcdiag#193]
**What problem would you like to address?** 
As outlined in our [data collection PRD](https://docs.google.com/document/d/1yCoD2EAIoi6w89IJ4aefAAAssDd75fQRzffvT10H5xM/edit#), understanding how our customers choose to build their TFE environments is very important so that we can 1) make recommendations for improvements, 2) understand if we need to update our documentation for clarity around infrastructure requirements, 3) build our test environments to be similar to those of our customers. Having cloud platform level information would be very nice to know so that we can focus our efforts in the right direction. For instance, if 90% of our customers are using Google Cloud Platform, then we can focus most of our testing efforts on GCP. This can be made possible by gathering the cloud metadata from a vm instance as described below.

**Who is the audience for this request?**  
TFE engineering

**Which HashiCorp products does this affect?**  
TFE and any other product that has an enterprise offering which the customer builds themselves

**What would the ideal solution look like?**  
[AWS](https://www.google.com/url?q=https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html&sa=D&source=docs&ust=1660171348773581&usg=AOvVaw13QvsYL9GXPcBfzIvMVWlk), [Azure](https://www.google.com/url?q=https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs%3Dlinux&sa=D&source=docs&ust=1660171348773757&usg=AOvVaw2idbwSzXtfDyUbZv2ztHo1), [GCP](https://cloud.google.com/compute/docs/metadata/default-metadata-values), and VMware virtual machines all have metadata services that are available even in an internal, air-gapped network that can be accessed to find metadata about the virtual machine from which you are querying the metadata service. 

For each of the clouds, you simply curl the local metadata server with a generic url, like this Azure example (specific metadata endpoints are linked above):

```bash
curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01"
```

It is my understanding that a `product` in `hcdiag` is a set of runners within a category. Therefore, I would want to create a new `product` called `cloud` where `NewCloud` would return a `product` using its runners, and I would have 1 runner which corresponded to the right cloud provider.

In the proposed structure below, the `cloud` product would also include a method to figure out which cloud the vm is in. It would then returns a `product` struct with the runner of the appropriate cloud in it. And it would be run inside the `agent`.

<img width="600" alt="cloud" src="https://user-images.githubusercontent.com/18335499/184408204-e43e4fea-c2f8-4638-9622-736235f6a0bd.png">

While it may be slightly different for each cloud platform, we would need to decide on the list of data to gather. For example:
* cloud platform
* image / image size
* region
* storage account type
* loadbalancer

**What alternatives have you considered?**  
I considered building this inside the TFE `product`, but it's much too hefty for that and also I believe that this is something that other teams will appreciate.

**How does this impact you?**  
This is part of a new initiative to gather data about our customers' environments. The impact of not being able to do this is that we cannot achieve the full benefits from this [PRD](https://docs.google.com/document/d/1yCoD2EAIoi6w89IJ4aefAAAssDd75fQRzffvT10H5xM/edit#).

**Are there any deadlines?**  
We would like to have this implemented by the end of Q3. If this does not fit into your roadmap by then, then I'm happy to work on it myself. 😃 

**Is there any additional context?**  
Context for this effort is in the [TF-553](https://docs.google.com/document/d/1rq6wvO8lfYya30zIZUKI7bmofDvhkyUkXt-YrwJe3SU/edit?usp=sharing) RFC. I'm also going to tag @roooms in case he'd like to comment on any use cases that he may find for this feature.

**Comment by roooms** [comment]
Thanks for including me on this. Yes, CS/WWFO would also really benefit from being able to gather this information. We really want to understand the customer environment so we can assess if the customer has followed our reference architecture guidance. This is something the technical roles on the CS and SEA team would then help the customer course-correct if they are a long way off what we recommend. This environmental information would also be fed into our CRM (Gainsight) so we can conduct cohort analysis on our customer base to look for patterns eg groups of customers with similar environments who onboard more quickly or more slowly, or who raise more or fewer support tickets. There's so much CS can do with this extra level of detail.

**Comment by aliciaclark1066** [comment]
Thanks for reporting! This ticket is outside of hcdiag's future scope, so I'm closing.
