### ISSUE TITLE
Add Additional Nomad Debug Options: -log-level, -max-nodes, -node-id, -server-id

### ISSUE THREAD

**Issue by MikaelHashiCorp** [hashicorp/hcdiag#224]
**What problem would you like to address?**  

Limited to only setting `nomad operator debug` parameters  [-duration](https://www.nomadproject.io/docs/commands/operator/debug#duration-2m) (`debug-duration`) and [-interval](https://www.nomadproject.io/docs/commands/operator/debug#interval-30s) (`debug-interval`).  I would like the following Nomad [debug options](https://www.nomadproject.io/docs/commands/operator/debug#debug-options) added:
* [-log-level](https://www.nomadproject.io/docs/commands/operator/debug#log-level-debug), TRACE level would be more helpful than DEBUG.
* [-max-nodes](https://www.nomadproject.io/docs/commands/operator/debug#max-nodes), there are times I need the customer to get **all** of their nodes in a region, not just 10.
* [-node-id](https://www.nomadproject.io/docs/commands/operator/debug#node-id), sometimes I need specific nodes to capture the data from, especially if they have 50 or 100 nodes in the region, and I need to target specific ones.
* [-server-id](https://www.nomadproject.io/docs/commands/operator/debug#server-id), same as for nodes.

**Who is the audience for this request?**  

Support Engineers

**Which HashiCorp products does this affect?**  

Nomad

**What would the ideal solution look like?**  

hcdiag -nomad -debug-duration 00h010m00s -debug-interval 00h01m00s -debug-log-level=TRACE -debug-max-nodes=100 

hcdiag -nomad -debug-duration 00h010m00s -debug-interval 00h01m00s -debug-log-level=TRACE -debug-node-id=abcd0123,zyxw9876 debug--server-id]=efgh4567,vuts5432

**What alternatives have you considered?**  

* Ask the customer to open two terminal shell sessions, run `nomad operator debug` in one and `hcdiag` in the other, at the same time.

**How does this impact you?**  

Many customers stumble with any complexity beyond one terminal window.

**Are there any deadlines?**  

No

**Is there any additional context?**  

No

**Comment by MikaelHashiCorp** [comment]
Workaround reported in https://hashicorp.atlassian.net/browse/DIAG-73

**Comment by groovemonkey** [comment]
I've added some extra examples relevant to this issue to the [custom config docs](https://github.com/hashicorp/hcdiag/blob/main/docs/custom-config.md). Closing this ticket for now -- it's unlikely that we'll implement a fully-configurable nomad debug log construct in hcdiag's code, since adding a custom command is straightforward and infinitely configurable.
