### ISSUE TITLE
Associate Manifest and Results

### ISSUE THREAD

**Issue by ml4** [hashicorp/hcdiag#244]
**What problem would you like to address?**  
In order to glean trends and changes to use of a tool over time, I am writing processing code to iterate pairs of `Manifest` and `Results` files and establish changes over time.  As a directory would thus contain multiple sets of `Manifest_vault_date.json`/`Results_vault_date.json` files etc, and because these names could be anything, I need a programmatic way to identify a `Manifest` from a `Results` from inside the files, and I also need to associate each `Manifest` with its respective `Results`.

**Who is the audience for this request?**  
Those most actively working on the Go code in the repo.

**Which HashiCorp products does this affect?**  
All

**What would the ideal solution look like?**  
I propose two changes:
In the JSON contents for the files, addition of the identification of the file type and identification of the run such as at the top of the `Manifest.json` and `Results.json` files respectively:

```json
{
    "type": "manifest",                                          <----- New entry
    "run_id": "d29c55ef-a5a1-4792-a077-76cdaf856800",            <----- New entry
    "started_at": "2022-10-04T10:14:18.638951961+01:00",
    "ended_at": "2022-10-04T10:14:20.89051098+01:00",
    "duration": "2.251559007 seconds",
    "num_ops": 31,
    "configuration": {
        "hcl": {
...
```

and

```json
{
    "type": "results",                                            <----- New entry
    "run_id": "d29c55ef-a5a1-4792-a077-76cdaf856800",            <----- New entry
    "host": {
...
```

**What alternatives have you considered?**  
I considered amalgamation of the `Manifest` and `Results` file, which would obviate the need to have the `run_id`, but without knowing Golang, I suspect that the effort involved would be quite painful.

**How does this impact you?**  
I cannot process pairs of `Manifest`/`Results` files into a trend analysis which helps track growth in the use of my HashiCorp tooling.

**What are the customer data privacy implications for this request?**
None.

**Are there any deadlines?**
None currently.

**Is there any additional context?**  
NA

**Comment by mkcp** [comment]
Closing issue -- the unique ID requested by runID is currently met with the bundle timestamp. A compound ID utilizing hostname + timestamp may be revisited in future hcdiag versions, esp. to meet cluster support requirements.
