### ISSUE TITLE
Add yum runner

### ISSUE THREAD

**Issue by ml4** [hashicorp/hcdiag#253]
**What problem would you like to address?**  
I see `dpkg-query -W vault-enterprise` in the Vault Results.json but nothing to do with yum.  

**Who is the audience for this request?**  
Developers

**Which HashiCorp products does this affect?**  
Probably all, definitely Vault.

**What would the ideal solution look like?**  
RHEL machines will be used by the overwhelming number of enterprise clients, so yum should be supported in addition to dpkg.

**What alternatives have you considered?**  
Snap and DNF might be worth thinking about. 

**How does this impact you?**  
I'm adding logic into hero to cater for dpkg running on RHEL. It would be good to autodetect, but that's a different issue.

**What are the customer data privacy implications for this request?**
NA

**Are there any deadlines?**
No

**Is there any additional context?**  
No

**Comment by aliciaclark1066** [comment]
The command runner is sufficient for this request. Closing issue.
