### ISSUE TITLE
Ingest Prometheus data when Consul emits metrics to Prometheus

### ISSUE THREAD

**Issue by david-yu** [hashicorp/hcdiag#75]
Currently hcdiag from my understanding ingests diagnostic data from API calls and the `consul debug` command. There are a couple of external data stores for Telemetry on Consul, however the most relevant of those is Prometheus see https://www.consul.io/docs/agent/telemetry

The hcdiag utility would somehow need to authenticate to the prometheus instance if it were secured over mTLS and also be able query for a specific timeframe within Prometheus to collect such metrics. The ideal outcome would be to output the metrics into a TSDB file so a support engineer could input the metrics back into a local Prometheus instance to be queried by Grafana (primarily for support troubleshooting with Consul). See https://github.com/prometheus/prometheus/pull/5887/files for an example of importing old data into prometheus. This would help tremendously with troubleshooting issues where a historical look of metrics are necessary to come to an RCA.

**Comment by aliciaclark1066** [comment]
Thanks for reporting! Based on hcdiag's future scope, we won't be doing this ticket.
